# Generated by Django 5.1.7 on 2025-03-27 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fqdn', models.CharField(max_length=255, unique=True)),
                ('rol', models.CharField(choices=[('controlador_primario', 'Controlador Primario'), ('miembro', 'Miembro del Dominio')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RolAnsible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaquinaVirtual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_vm', models.CharField(max_length=100)),
                ('hostname', models.CharField(max_length=100)),
                ('plantilla', models.CharField(max_length=100)),
                ('vlan', models.IntegerField()),
                ('ip_ultimo_octeto', models.IntegerField()),
                ('ram_gb', models.IntegerField(default=4)),
                ('cpus', models.IntegerField(default=2)),
                ('sistema_operativo', models.CharField(choices=[('windows', 'Windows'), ('linux', 'Linux'), ('macos', 'MacOS')], max_length=50)),
                ('dominio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configurador.dominio')),
                ('roles', models.ManyToManyField(blank=True, to='configurador.rolansible')),
            ],
        ),
    ]
