# Generated by Django 5.1.7 on 2025-03-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurador', '0002_maquinavirtual_roles_ansible_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
                ('archivo_configuracion', models.FileField(upload_to='archivos_configuracion/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
