# Generated by Django 5.1.7 on 2025-03-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurador', '0003_laboratorio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratorio',
            name='archivo_configuracion',
        ),
        migrations.RemoveField(
            model_name='laboratorio',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='archivo_config',
            field=models.FileField(blank=True, null=True, upload_to='configuraciones_laboratorios/'),
        ),
    ]
