# Generated by Django 5.1.7 on 2025-03-27 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurador', '0004_remove_laboratorio_archivo_configuracion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratorio',
            name='archivo_config',
        ),
        migrations.AddField(
            model_name='maquinavirtual',
            name='laboratorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vms', to='configurador.laboratorio'),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
