# Generated by Django 5.1.7 on 2025-03-28 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurador', '0005_remove_laboratorio_archivo_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorio',
            name='maquinas_virtuales',
            field=models.ManyToManyField(blank=True, related_name='laboratorios', to='configurador.maquinavirtual'),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='maquinavirtual',
            name='laboratorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maquinas', to='configurador.laboratorio'),
        ),
    ]
