# Generated by Django 5.1.7 on 2025-03-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurador', '0006_laboratorio_maquinas_virtuales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorio',
            name='configuracion',
            field=models.FileField(blank=True, null=True, upload_to='configuraciones/'),
        ),
    ]
