# Generated by Django 5.1.7 on 2025-03-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurador', '0007_laboratorio_configuracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorio',
            name='config',
            field=models.FileField(blank=True, null=True, upload_to='configuraciones/'),
        ),
    ]
