# Generated by Django 5.1.7 on 2025-03-28 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurador', '0008_laboratorio_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratorio',
            name='config',
        ),
    ]
