# Generated by Django 4.2.11 on 2025-03-31 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurador', '0010_sshconfiguracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionRed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inter_vlan_default', models.CharField(default='REJECT', max_length=10)),
                ('external_default', models.CharField(default='ACCEPT', max_length=10)),
                ('always_blocked_networks', models.JSONField(blank=True, default=list, null=True)),
                ('rules', models.JSONField(blank=True, default=list, null=True)),
                ('laboratorio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='configurador.laboratorio')),
            ],
        ),
    ]
