# Generated by Django 4.2.11 on 2025-03-31 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurador', '0011_configuracionred'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaRed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vlan_src', models.IntegerField()),
                ('vlan_dst', models.IntegerField()),
                ('protocolo', models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP'), ('icmp', 'ICMP'), ('all', 'All')], max_length=10)),
                ('ports', models.CharField(max_length=50)),
                ('action', models.CharField(choices=[('ACCEPT', 'ACCEPT'), ('REJECT', 'REJECT'), ('DROP', 'DROP')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='reglas_red',
            field=models.ManyToManyField(blank=True, related_name='laboratorios', to='configurador.reglared'),
        ),
    ]
