# Generated by Django 4.2.11 on 2025-04-01 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurador', '0012_reglared_laboratorio_reglas_red'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maquinavirtual',
            name='roles_ansible',
        ),
    ]
