# Generated by Django 4.2.11 on 2025-04-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurador', '0013_remove_maquinavirtual_roles_ansible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maquinavirtual',
            name='roles',
        ),
        migrations.AddField(
            model_name='maquinavirtual',
            name='roles_ansible',
            field=models.CharField(blank=True, choices=[('badsectorlabs.ludus_vulhub', 'Runs Vulhub environments on a Linux system.'), ('badsectorlabs.ludus_adcs', 'Installs ADCS on Windows Server and optionally configures Certified Preowned templates.'), ('badsectorlabs.ludus_bloodhound_ce', 'Installs Bloodhound CE on a Debian based system.'), ('badsectorlabs.ludus_mssql', 'Installs MSSQL on Windows systems.'), ('badsectorlabs.ludus_elastic_container', 'Installs "The Elastic Container Project" on a Linux system.'), ('badsectorlabs.ludus_elastic_agent', 'Installs an Elastic Agent on a Windows, Debian, or Ubuntu system'), ('badsectorlabs.ludus_xz_backdoor', 'Installs the xz backdoor (CVE-2024-3094) on a Debian host and optionally installs the xzbot tool.'), ('badsectorlabs.ludus_commandovm', 'Sets up Commando VM on Windows >= 10 hosts'), ('badsectorlabs.ludus_flarevm', 'Installs Flare VM on Windows >= 10 hosts'), ('badsectorlabs.ludus_remnux', 'Installs REMnux on Ubuntu 20.04 systems'), ('badsectorlabs.ludus_emux', 'Installs EMUX and runs an emulated device on Debian based hosts'), ('aleemladha.wazuh_server_install', 'Install Wazuh SIEM Unified XDR and SIEM protection with SOC Fortress Rules'), ('aleemladha.ludus_wazuh_agent', 'Deploys Wazuh Agents to Windows systems'), ('aleemladha.ludus_exchange', 'Installs Microsoft Exchange Server on a Windows Server host'), ('ludus_child_domain', "Create a child domain and domain controller because ansible's microsoft.ad doesn't support it"), ('ludus_child_domain_join', 'Join a machine to the child domain created from ludus_child_domain'), ('ludus-local-users', 'Manages local users and groups for Windows or Linux'), ('ludus-gitlab-ce', 'Handles the installation of a Gitlab instance'), ('ludus-ad-content', 'Creates content in an Active Directory (OUs, Groups, Users)'), ('ludus_tailscale', 'Provision or remove a device to/from a Tailnet'), ('ludus_velociraptor_client', 'Install a Velociraptor Agent on a System in Ludus'), ('ludus_velociraptor_server', 'Install a Velociraptor Server in Ludus'), ('bagelByt3s.ludus_adfs', 'Installs an ADFS deployment with optional configurations.'), ('ludus_caldera_server', 'Installs Caldera Server main branch on linux'), ('ludus_caldera_agent', 'Installs Caldera Agent on Windows'), ('ludus_aurora_agent', 'Installs Aurora Agent on Windows'), ('ludus_graylog_server', 'Installs Graylog server on Ubuntu 22.04'), ('0xRedpoll.ludus_cobaltstrike_teamserver', 'Install and provision a Cobalt Strike teamserver in Ludus'), ('0xRedpoll.ludus_mythic_teamserver', 'Installs and spins up a Mythic Teamserver on a Debian or Ubuntu server'), ('ludus-ad-vulns', 'Adds vulnerabilities in an Active Directory.'), ('ludus_juiceshop', 'Installs OWASP Juice Shop')], max_length=255, null=True),
        ),
    ]
