# Generated by Django 4.2.11 on 2025-04-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurador', '0014_remove_maquinavirtual_roles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinavirtual',
            name='roles_ansible',
            field=models.TextField(blank=True, null=True),
        ),
    ]
