# Generated by Django 4.2.11 on 2025-04-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurador', '0015_alter_maquinavirtual_roles_ansible'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinavirtual',
            name='roles',
            field=models.ManyToManyField(blank=True, to='configurador.rolansible'),
        ),
    ]
