# Generated by Django 4.2.11 on 2025-04-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurador', '0017_alter_maquinavirtual_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratorioPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo_configuracion', models.FileField(blank=True, null=True, upload_to='presset/')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
