# Generated by Django 4.2.11 on 2025-04-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurador', '0018_laboratoriopreset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratoriopreset',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='laboratoriopreset',
            name='archivo_configuracion',
        ),
        migrations.AlterField(
            model_name='laboratoriopreset',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
