# Generated by Django 4.2.11 on 2025-04-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurador', '0020_alter_maquinavirtual_plantilla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinavirtual',
            name='plantilla',
            field=models.CharField(choices=[('debian-11-x64-server-template ', 'Debian 11'), ('debian-12-x64-server-template ', 'Debian 12'), ('kali-x64-desktop-template  ', 'Kali Linux'), ('win11-22h2-x64-enterprise-template', 'Windows 11 (22H2 Enterprise)'), ('win2022-server-x64-template', 'Windows 2022 Server (x64)'), ('debian10-template', 'Debian 10'), ('rocky-9-x64-server-template', 'Rocky 9 (x64 Server)'), ('ubuntu-20.04-x64-server-template', 'Ubuntu 20.04 (x64 Server)'), ('ubuntu-22.04-x64-server-template', 'Ubuntu 22.04 (x64 Server)'), ('win10-21h1-x64-enterprise-template', 'Windows 10 (21H1 Enterprise)'), ('win11-23h2-x64-enterprise-template', 'Windows 11 (23H2 Enterprise)'), ('win2012r2-server-x64-template', 'Windows 2012 R2 Server (x64)'), ('win2016-server-x64-template', 'Windows 2016 Server (x64)'), ('win2019-server-x64-template', 'Windows 2019 Server (x64)'), ('commando-vm-template', 'Commando VM (requires ansible role: badsectorlabs.ludus_commandovm)'), ('flare-vm-template', 'Flare VM (requires ansible role: badsectorlabs.ludus_flarevm)'), ('remnux-template', 'Remnux (requires ansible role: badsectorlabs.ludus_remnux)')], max_length=100),
        ),
    ]
